In [ ]:
# RESUME_CLASSIFICATION_PROJECT_CHROMADB/
# │
# ├── Education/          # 5000 resume PDFs
# ├── JD_Matches/         # job descriptions
# ├── chroma_db/          # ChromaDB will be saved here later
# ├── models/             # ML models will be saved here
# └── Resume_Classification_and_Matching_System.ipynb

In [25]:
import os
import fitz
import pandas as pd
import numpy as np

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans

import joblib

In [26]:
print(os.getcwd())
print(os.listdir())

print("Total resumes:", len(os.listdir("Education")))

c:\Users\AFISHA AZME\OneDrive\Documents\RESUME_CLASSIFICATION_PROJECT_CHROMADB
['.venv', 'chroma_db', 'Education', 'JD_Matches', 'models', 'Resume_Classification_and_Matching_System.ipynb']
Total resumes: 5000

In [27]:
def extract_text(pdf_path):
    text = ""

    try:
        doc = fitz.open(pdf_path)

        for page in doc:
            text += page.get_text()

    except Exception as e:
        print("Error:", pdf_path)

    return text.strip()

In [28]:
resume_names = []
resume_texts = []

for file in os.listdir("Education"):

    if file.lower().endswith(".pdf"):

        path = os.path.join("Education", file)

        text = extract_text(path)

        if len(text) > 100:
            resume_names.append(file)
            resume_texts.append(text)

print("Loaded resumes:", len(resume_names))
print("Sample resume text:", resume_texts[0][:500])

Loaded resumes: 5000
Sample resume text: Lori Hart
lori.hart30001@reed-kennedy.com | (538)274-8914x081 | 4458 Perez Mountains Suite 094, Lake Debra, MH
88430 | linkedin.com/in/lori-hart-30001
PROFESSIONAL SUMMARY
Experienced professional with a strong background in Education and expertise in Agile, Python, AWS. Proven
track record of delivering high-quality results in fast-paced environments. Excellent Leadership, Attention to
Detail skills with a passion for continuous learning and professional development.
PROFESSIONAL EXPERIENCE
Sof

In [29]:
df = pd.DataFrame({
    "resume_name": resume_names,
    "text": resume_texts
})

df.head()

,resume_name,text
0,Resume_030001_Lori_Hart.pdf,Lori Hart\nlori.hart30001@reed-kennedy.com | (...
1,Resume_030002_Anthony_Moses.pdf,Anthony Moses\nanthony.moses30002@scott.com | ...
2,Resume_030003_Edward_Shepherd.pdf,Edward Shepherd\nedward.shepherd30003@marshall...
3,Resume_030004_Nicholas_Potter.pdf,Nicholas Potter\nnicholas.potter30004@wiley.or...
4,Resume_030005_Donna_Watts.pdf,Donna Watts\ndonna.watts30005@wells-gonzalez.c...

In [30]:
tfidf = TfidfVectorizer(
    max_features=5000,
    stop_words="english"
)

X = tfidf.fit_transform(df["text"])

print("TF-IDF shape:", X.shape)

TF-IDF shape: (5000, 5000)

In [31]:
kmeans = KMeans(
    n_clusters=5,
    random_state=42,
    n_init=10
)

df["cluster"] = kmeans.fit_predict(X)

df.head()

,resume_name,text,cluster
0,Resume_030001_Lori_Hart.pdf,Lori Hart\nlori.hart30001@reed-kennedy.com | (...,2
1,Resume_030002_Anthony_Moses.pdf,Anthony Moses\nanthony.moses30002@scott.com | ...,1
2,Resume_030003_Edward_Shepherd.pdf,Edward Shepherd\nedward.shepherd30003@marshall...,1
3,Resume_030004_Nicholas_Potter.pdf,Nicholas Potter\nnicholas.potter30004@wiley.or...,3
4,Resume_030005_Donna_Watts.pdf,Donna Watts\ndonna.watts30005@wells-gonzalez.c...,2

In [32]:
df["cluster"].value_counts()

cluster
2    1814
3    1159
1    1120
0     779
4     128
Name: count, dtype: int64

In [33]:
terms = tfidf.get_feature_names_out()

for i in range(5):
    center = kmeans.cluster_centers_[i]
    top_words = np.array(terms)[center.argsort()[-20:]]

    print("\nCluster", i)
    print(top_words)

Cluster 0
['node' 'scrum' 'gpa' 'university' 'excellent' 'analysis' 'time' 'project'
 'strong' 'learning' 'management' 'architect' 'solutions' 'certified'
 'data' 'technologies' 'education' 'aws' 'skills' 'professional']

Cluster 1
['communication' 'aws' 'machine' 'ci' 'cd' 'gpa' 'university' 'scrum'
 'excellent' 'time' 'data' 'project' 'strong' 'azure' 'learning'
 'management' 'technologies' 'education' 'skills' 'professional']

Cluster 2
['analysis' 'manager' 'machine' 'engineer' 'gpa' 'university' 'scrum'
 'excellent' 'azure' 'devops' 'time' 'learning' 'strong' 'project'
 'management' 'data' 'technologies' 'education' 'skills' 'professional']

Cluster 3
['azure' 'python' 'machine' 'kubernetes' 'project' 'scrum' 'devops'
 'excellent' 'time' 'analysis' 'university' 'gpa' 'strong' 'learning'
 'management' 'data' 'technologies' 'education' 'skills' 'professional']

Cluster 4
['azure' 'javascript' 'devops' 'git' 'scrum' 'time' 'docker' 'gpa'
 'university' 'excellent' 'strong' 'project' 'learning' 'data'
 'management' 'technologies' 'education' 'skills' 'professional' 'michael']

In [34]:
print(df["cluster"].value_counts())

cluster
2    1814
3    1159
1    1120
0     779
4     128
Name: count, dtype: int64

terms = tfidf.get_feature_names_out()

for i in range(5):
    center = kmeans.cluster_centers_[i]
    top_words = np.array(terms)[center.argsort()[-20:]]

    print("\nCluster", i)
    print(top_words)

In [41]:
custom_stop_words = [
    "professional", "skills", "education", "technologies",
    "excellent", "strong", "university", "gpa",
    "project", "time", "learning", "management",
    "experience", "background", "results"
]

tfidf = TfidfVectorizer(
    max_features=5000,
    stop_words="english",
    max_df=0.70,
    min_df=5
)

X = tfidf.fit_transform(df["text"])

kmeans = KMeans(
    n_clusters=5,
    random_state=42,
    n_init=10
)

df["cluster"] = kmeans.fit_predict(X)

print(df["cluster"].value_counts())

cluster
4    2008
1    1864
0     854
3     169
2     105
Name: count, dtype: int64

In [42]:
terms = tfidf.get_feature_names_out()

for i in range(5):
    center = kmeans.cluster_centers_[i]
    top_words = np.array(terms)[center.argsort()[-25:]]

    print("\nCluster", i)
    print(top_words)

Cluster 0
['product' 'ph' 'administrator' '2019' 'master' 'christopher' 'analyst'
 'ethic' 'adaptability' 'leadership' 'certified' 'science' 'teamwork'
 'business' 'manager' 'critical' 'thinking' 'work' 'creativity' 'engineer'
 'attention' '2023' '2022' 'certification' 'pmp']

Cluster 1
['conversational' 'manager' 'native' 'ph' 'fluent' 'bachelor' 'basic'
 'associate' 'engineer' 'administrator' 'business' 'science' 'teamwork'
 'adaptability' 'creativity' 'leadership' 'critical' 'ethic' 'thinking'
 '2022' 'attention' 'master' 'work' '2023' 'certified']

Cluster 2
['scientist' 'cloud' 'google' 'administrator' 'group' 'adaptability'
 'source' 'master' 'ethic' 'creativity' 'business' 'product' 'leadership'
 'basic' '2023' 'critical' 'teamwork' 'attention' 'manager' 'thinking'
 'work' 'engineer' '2022' 'certified' 'james']

Cluster 3
['scientist' 'analyst' 'native' 'fluent' 'master' 'conversational'
 'business' 'administrator' 'creativity' 'leadership' 'ethic' 'critical'
 'thinking' 'teamwork' 'product' '2023' 'work' 'engineer' 'adaptability'
 'attention' '2022' 'manager' 'certified' 'robert' 'david']

Cluster 4
['software' 'administration' '2018' 'critical' 'leadership' 'ethic'
 'creativity' 'science' 'adaptability' 'thinking' 'teamwork' 'group'
 '2023' 'scientist' 'product' 'master' '2022' 'administrator' 'work'
 'certified' 'analyst' 'attention' 'business' 'manager' 'engineer']

In [43]:
df["category"] = "Cluster_" + df["cluster"].astype(str)

df.head()

,resume_name,text,cluster,category
0,Resume_030001_Lori_Hart.pdf,Lori Hart\nlori.hart30001@reed-kennedy.com | (...,4,Cluster_4
1,Resume_030002_Anthony_Moses.pdf,Anthony Moses\nanthony.moses30002@scott.com | ...,0,Cluster_0
2,Resume_030003_Edward_Shepherd.pdf,Edward Shepherd\nedward.shepherd30003@marshall...,1,Cluster_1
3,Resume_030004_Nicholas_Potter.pdf,Nicholas Potter\nnicholas.potter30004@wiley.or...,1,Cluster_1
4,Resume_030005_Donna_Watts.pdf,Donna Watts\ndonna.watts30005@wells-gonzalez.c...,4,Cluster_4

In [44]:
df["category"].value_counts()

category
Cluster_4    2008
Cluster_1    1864
Cluster_0     854
Cluster_3     169
Cluster_2     105
Name: count, dtype: int64

In [45]:
import joblib

joblib.dump(tfidf, "models/tfidf_vectorizer.pkl")
joblib.dump(kmeans, "models/kmeans_model.pkl")

df.to_csv("clustered_resumes.csv", index=False)

print("Saved model and clustered resumes")

Saved model and clustered resumes

Task 2: Create ChromaDB collection

In [46]:
import chromadb

client = chromadb.PersistentClient(path="chroma_db")

collection = client.get_or_create_collection(
    name="resume_collection"
)

print("Collection created")

Collection created

In [47]:
ids = []
documents = []
metadatas = []

for i, row in df.iterrows():

    ids.append(str(i))

    documents.append(row["text"][:5000])

    metadatas.append({
        "resume_name": row["resume_name"],
        "category": row["category"],
        "cluster": int(row["cluster"])
    })

collection.add(
    ids=ids,
    documents=documents,
    metadatas=metadatas
)

print("Total documents in ChromaDB:", collection.count())

C:\Users\AFISHA AZME\.cache\chroma\onnx_models\all-MiniLM-L6-v2\onnx.tar.gz: 100%|██████████| 79.3M/79.3M [00:33<00:00, 2.51MiB/s]

Total documents in ChromaDB: 5000

In [48]:
results = collection.get(
    where={"category": "Cluster_0"},
    limit=3
)

results["metadatas"]

[{'resume_name': 'Resume_030002_Anthony_Moses.pdf',
  'category': 'Cluster_0',
  'cluster': 0},
 {'category': 'Cluster_0',
  'cluster': 0,
  'resume_name': 'Resume_030008_Alexander_Huang.pdf'},
 {'resume_name': 'Resume_030011_Kyle_George.pdf',
  'category': 'Cluster_0',
  'cluster': 0}]

In [49]:
def match_jd_to_resumes(job_description, top_k=3):

    jd_vector = tfidf.transform([job_description])

    predicted_cluster = kmeans.predict(jd_vector)[0]

    predicted_category = "Cluster_" + str(predicted_cluster)

    results = collection.query(
        query_texts=[job_description],
        n_results=top_k,
        where={"category": predicted_category}
    )

    print("Predicted Category:", predicted_category)
    print("\nTop 3 Matched Resumes:")

    for i in range(top_k):
        print("\nRank:", i + 1)
        print("Resume:", results["metadatas"][0][i]["resume_name"])
        print("Category:", results["metadatas"][0][i]["category"])
        print("Distance:", results["distances"][0][i])

    return results

In [50]:
jd = """
We are hiring a DevOps Engineer with Docker, Kubernetes, Jenkins,
CI/CD, AWS, Azure, Linux and cloud deployment experience.
"""

match_jd_to_resumes(jd)

Predicted Category: Cluster_1

Top 3 Matched Resumes:

Rank: 1
Resume: Resume_032481_Christopher_Smith.pdf
Category: Cluster_1
Distance: 0.8307478427886963

Rank: 2
Resume: Resume_032575_Kevin_Armstrong.pdf
Category: Cluster_1
Distance: 0.8319547176361084

Rank: 3
Resume: Resume_031306_Devin_Wallace.pdf
Category: Cluster_1
Distance: 0.8547893166542053

{'ids': [['2480', '2574', '1305']],
 'embeddings': None,
 'documents': [["Christopher Smith\nchristopher.smith32481@haynes-navarro.com | +1-431-952-0373x856 | 184 Brandy Isle, Hillshire, SD 36188 |\nlinkedin.com/in/christopher-smith-32481\nPROFESSIONAL SUMMARY\nExperienced professional with a strong background in Education and expertise in Docker, Scrum, Git. Proven\ntrack record of delivering high-quality results in fast-paced environments. Excellent Critical Thinking,\nCommunication skills with a passion for continuous learning and professional development.\nPROFESSIONAL EXPERIENCE\nDevOps Engineer | Thompson and Sons | 2022 - 2024\n• Finally everyone read kind word research defense.\n• Father look or mouth.\n• House scene sometimes until their outside style past.\n• Behavior production wrong future let.\nDevOps Engineer | Lee, Ray and Hudson | 2018 - Present\n• Though population cold receive four happen.\n• Authority woman economic story seek.\n• However compare order team strong run already recent.\n• Rise toward when special street in.\nEDUCATION\nBachelor's in Computer Science | Dickerson-Wells University | GPA: 3.34 | 2020\nTECHNICAL SKILLS\nDocker | Scrum | Git | Data Analysis | React | MongoDB | CI/CD\nSOFT SKILLS\nCritical Thinking | Communication | Work Ethic | Attention to Detail | Time Management | Problem Solving |\nCreativity\nKEY PROJECTS\nExpanded optimizing migration\nLong culture society moment. Save white animal. Opportunity star buy call response skin either.\nTechnologies: Azure, Agile, Kubernetes, C++, DevOps, Machine Learning\nOrganized impactful artificial intelligence\nBeautiful wish newspaper of international against. Think assume travel.\nTechnologies: Data Analysis, Agile, Docker, React, SQL\nMandatory eco-centric moratorium\nSometimes west politics effort model it rather.\nTechnologies: AWS, Kubernetes, JavaScript, Docker, Project Management\nErgonomic web-enabled toolset\nHand just pass. Group sense yes.\nTechnologies: JavaScript, Node.js, Python\nCERTIFICATIONS\n• AWS Certified Solutions Architect (2023)\n• Google Cloud Professional (2024)\n• AWS Certified Solutions Architect (2024)\nLANGUAGES\nGerman (Fluent) | Arabic (Fluent) | Spanish (Fluent)\nADDITIONAL INFORMATION\nCourse Focus: Education | Available for full-time positions | Willing to relocate | Strong analytical and\nproblem-solving abilities | Excellent written and verbal communication skills",
   "Kevin Armstrong\nkevin.armstrong32575@calderon-butler.net | 574-620-8445x107 | 011 Brent Mountain Apt. 884, Kathrynland,\nAL 66282 | linkedin.com/in/kevin-armstrong-32575\nPROFESSIONAL SUMMARY\nExperienced professional with a strong background in Education and expertise in DevOps, Docker, Kubernetes.\nProven track record of delivering high-quality results in fast-paced environments. Excellent Time Management,\nCreativity skills with a passion for continuous learning and professional development.\nPROFESSIONAL EXPERIENCE\nSystems Administrator | Weaver-Ellis | 2021 - 2024\n• Catch garden two to majority get moment safe.\n• Society must yourself lose development marriage hard wish plant marriage.\n• Suffer nothing nature want action where phone.\n• Resource job modern avoid whom.\n• Night eight mouth discussion party federal.\n• Good look win hair pattern consider.\nDevOps Engineer | Price, Hernandez and Mckay | 2018 - Present\n• Let eight hotel remain.\n• Race should treat role star bit account test much.\n• Exactly summer study my bed.\n• Own run available card store.\nEDUCATION\nBachelor's in Statistics | Galloway-Hogan University | GPA: 3.83 | 2021\nPh.D. in Economics | Johnson-Rasmussen University | GPA: 3.31 | 2017\nTECHNICAL SKILLS\nDevOps | Docker | Kubernetes | Scrum | Azure | AWS | Python | Java | Machine Learning | MongoDB | C++ |\nData Analysis\nSOFT SKILLS\nTime Management | Creativity | Problem Solving | Attention to Detail | Adaptability | Work Ethic | Critical\nThinking\nKEY PROJECTS\nSynergistic bottom-line policy\nAhead people successful positive save. Drive real source treat north. Each interesting popular. Road save\ntrouble various stock shoulder.\nTechnologies: Python, Scrum, Agile\nSynergized zero tolerance process improvement\nPoint hour reality. Tend suggest decision improve believe his like. Break cause because must company fire\nculture.\nTechnologies: Git, Python, Data Analysis, Agile, DevOps, Docker\nCERTIFICATIONS\n• Google Cloud Professional (2022)\n• Certified Scrum Master (2023)\n• CISSP (2022)\n• Google Cloud Professional (2024)\nLANGUAGES\nHindi (Fluent) | Mandarin (Native) | Arabic (Conversational)\nADDITIONAL INFORMATION\nCourse Focus: Education | Available for full-time positions | Willing to relocate | Strong analytical and\nproblem-solving abilities | Excellent written and verbal communication skills",
   "Devin Wallace\ndevin.wallace31306@gilmore.info | (897)524-4442 | USCGC Cannon, FPO AE 43679 |\nlinkedin.com/in/devin-wallace-31306\nPROFESSIONAL SUMMARY\nExperienced professional with a strong background in Education and expertise in Kubernetes, MongoDB,\nReact. Proven track record of delivering high-quality results in fast-paced environments. Excellent Problem\nSolving, Critical Thinking skills with a passion for continuous learning and professional development.\nPROFESSIONAL EXPERIENCE\nDevOps Engineer | Snyder and Sons | 2020 - 2024\n• Order center about decide cut ask.\n• Collection section smile least today.\n• Determine record everything value agree staff office though speech.\n• Sort believe task recently happen management.\n• At also security dream share game.\nQuality Assurance Engineer | Powell, Jones and Gutierrez | 2014 - Present\n• Need forward today relationship home step reveal yeah create wide.\n• Result player situation amount provide a very able act discover.\n• Serious fall still million civil argue treatment usually night.\n• Put go paper issue wrong year speak dream kitchen.\n• Public instead mouth machine society lawyer.\nEDUCATION\nBachelor's in Economics | Estes and Sons University | GPA: 3.78 | 2018\nTECHNICAL SKILLS\nKubernetes | MongoDB | React | Data Analysis | Node.js | JavaScript | AWS | Docker\nSOFT SKILLS\nProblem Solving | Critical Thinking | Communication | Creativity | Adaptability | Work Ethic\nKEY PROJECTS\nUniversal transitional intranet\nHeavy outside ever. New term before turn plant.\nTechnologies: SQL, Node.js, MongoDB\nCross-platform logistical Internet solution\nResearch public grow by can inside discuss. We pick throughout officer people risk tree.\nTechnologies: Node.js, Kubernetes, MongoDB\nAssimilated even-keeled attitude\nParent these game bit. Page case break. Always ready item size.\nTechnologies: JavaScript, Scrum, Java, React\nCERTIFICATIONS\n• CISSP (2023)\nLANGUAGES\nEnglish (Fluent) | German (Native)\nADDITIONAL INFORMATION\nCourse Focus: Education | Available for full-time positions | Willing to relocate | Strong analytical and\nproblem-solving abilities | Excellent written and verbal communication skills"]],
 'uris': None,
 'included': ['metadatas', 'documents', 'distances'],
 'data': None,
 'metadatas': [[{'cluster': 1,
    'category': 'Cluster_1',
    'resume_name': 'Resume_032481_Christopher_Smith.pdf'},
   {'resume_name': 'Resume_032575_Kevin_Armstrong.pdf',
    'category': 'Cluster_1',
    'cluster': 1},
   {'cluster': 1,
    'category': 'Cluster_1',
    'resume_name': 'Resume_031306_Devin_Wallace.pdf'}]],
 'distances': [[0.8307478427886963, 0.8319547176361084, 0.8547893166542053]]}